import type { FC } from "react";

/**
 * The blurred chapter shown behind a paywall overlay on a locked section.
 *
 * WHY AN IMAGE AND NOT DOM
 * A locked section has to look like a real chapter sits behind the overlay. If
 * that content were DOM with `filter: blur()` over it, the blur would be nothing
 * but a paint effect — deleting one CSS line in DevTools hands over the paid
 * chapter. These are pre-rasterised renders of the REAL chapter whose pixels
 * were blurred and downsampled at build time, so the words are not in the file
 * that ships and there is nothing to recover.
 *
 * Generated by `scripts/generate-locked-previews.mjs`; see it for how the blur
 * is matched to `--report-lock-blur`.
 */
const LockedPreviewImage: FC<{ name: string }> = ({ name }) => (
  <picture className="report-locked-preview">
    <source media="(max-width: 768px)" srcSet={`/report-previews/${name}-mobile.jpg`} />
    <img
      className="report-locked-preview__img"
      src={`/report-previews/${name}-desktop.jpg`}
      alt=""
      aria-hidden="true"
      // Eager on purpose. These are ~3KB each and they ARE the backdrop: a
      // preview that has not loaded yet is an empty box behind the paywall,
      // which is the exact bug this replaced. `fetchPriority="low"` keeps them
      // out of the way of anything that actually blocks rendering.
      loading="eager"
      fetchPriority="low"
      decoding="async"
      draggable={false}
    />
  </picture>
);

export default LockedPreviewImage;
