import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Every locked premium section shows a pre-blurred render of its REAL chapter
 * behind the paywall overlay, generated by scripts/generate-locked-previews.mjs.
 *
 * Two things can silently break this and neither shows up in a type check:
 *  1. A section drifts back to stand-in DOM, or forgets the `--image` modifier
 *     and double-blurs the already-blurred pixels.
 *  2. An image file goes missing, which renders as an EMPTY box behind the
 *     paywall — the exact "there's nothing behind it" bug this replaced.
 *
 * Rendering all sixteen sections would need sixteen prop fixtures, so this
 * checks the source and the assets directly.
 *
 * BeliefsSection and AcceleratorsSection are not in the registry below because
 * their shape is different: they
 * shows its first two beliefs as LIVE text (Figma's locked frame keeps that
 * chapter's top rows crisp) and then one raster PER COLUMN for the rows past them
 * — a keep row is 51px against a loosen row's 111px, so a single whole-chapter
 * raster could not line up with both. It also keeps its own wrapper rather than
 * `--image`, since only part of the column is pixels. See
 * BeliefsSection.locked.test.tsx.
 */
const COLUMN_PREVIEWS: Record<string, string[]> = {
  "BeliefsSection.tsx": ["beliefs-keep", "beliefs-loosen"],
  "AcceleratorsSection.tsx": ["accel-opens", "accel-shuts", "accel-tail"],
  // Attachment locks in two places — the result card (behind the paywall card) and
  // the map with its caption — with the universal learn pill, map eyebrow and Learn
  // expander staying live between them, so it cannot be one whole-chapter raster.
  "AttachmentPatternsSection.tsx": ["attach-card", "attach-map"],
  // The three gold "practical" expanders' teaser, on top of each chapter's own
  // whole-section raster in SECTIONS below: their teaser is per-archetype and withheld,
  // so it ships as pixels in the slot the eleven universal expanders fill with text.
  "InsecuritiesSection.tsx": ["practical-insecurities"],
  "InitiationSection.tsx": ["practical-initiation"],
  "LibidoSection.tsx": ["practical-libido"],
};
const COLUMN_PREVIEW_NAMES = Object.values(COLUMN_PREVIEWS).flat();
const SECTIONS_DIR = join(process.cwd(), "features/report/ui/sections");
/** asset name -> CSS class prefix, where the two differ. */
const SECTION_SCOPES: Record<string, string> = { reading: "reading", lovelang: "lovelang" };
const PREVIEW_DIR = join(process.cwd(), "public/report-previews");

/** section component file -> preview asset name */
const SECTIONS: Record<string, string> = {
  "ArousalSection.tsx": "arousal",
  "ConfidenceSection.tsx": "confidence",
  "CuriositySection.tsx": "curiosity",
  "EnergySection.tsx": "energy",
  "FantasySection.tsx": "fantasy",
  "GrowthSection.tsx": "growth",
  "InitiationSection.tsx": "initiation",
  "InsecuritiesSection.tsx": "insecurities",
  "LibidoSection.tsx": "libido",
  "LoveLanguageSection.tsx": "lovelang",
  "PartnershipSection.tsx": "partnership",
  "PowerSection.tsx": "power",
  "ReadingSection.tsx": "reading",
  "RewardSection.tsx": "reward",
};

describe("locked preview images", () => {
  it("shows the WHOLE chapter, not the top of it", () => {
    // The boxes used to be sized by the paywall CARD, with the raster an absolute
    // backdrop cropped to fit (`object-fit: cover`). That was right when the backdrop
    // was a short piece of stand-in DOM; with a raster of the real chapter it cut the
    // chapter off — 626px of a 1332px fantasy chapter, 52-83% for the rest.
    //
    // Both children now share ONE grid cell, so the box is as tall as the taller of
    // the two: no crop, and no min-height to keep in step with the card.
    const css = readFileSync(join(process.cwd(), "app/globals.css"), "utf8");
    const at = css.indexOf("THE WHOLE CHAPTER SHOWS, NOT THE TOP OF IT");
    expect(at, "the shared grid rule is gone").toBeGreaterThan(-1);
    const block = css.slice(at, at + 9000);
    for (const name of Object.values(SECTIONS)) {
      const scope = SECTION_SCOPES[name] ?? name;
      expect(block, `${name} is not in the grid rule`).toContain(`.report-${scope}__preview`);
    }
    expect(block).toContain("display: grid");
    expect(block).toContain("grid-area: 1 / 1");
    expect(block).toContain("align-self: start");
    // ...and the base rule's crop is overridden for them.
    expect(block).toContain("height: auto");
    expect(block).toContain("object-fit: fill");
  });

  it("waits for a chapter's reveal to finish before and after the DOM surgery", () => {
    // Two ways a capture shipped a half-drawn chapter:
    //  1. a flat wait. 2500ms was derived from the growth ladder's own timings and
    //     still fell short — measured, its last rung only reaches full opacity between
    //     2.5s and 4s, so the file held two of five rungs and read as an empty card.
    //  2. the wrapper. Moving the card's children into it RE-PARENTS them, which
    //     restarts their CSS animations from zero, so even a settled chapter was
    //     mid-reveal again at the moment of the screenshot.
    const gen = readFileSync(join(process.cwd(), "scripts/generate-locked-previews.mjs"), "utf8");
    expect(gen).not.toContain("REVEAL_SETTLE_MS");
    expect(gen).toContain("async function settleReveal(page, sectionId)");
    // Once before the wrapper goes in, once after — both capture paths.
    expect([...gen.matchAll(/await settleReveal\(page, sectionId\);/g)]).toHaveLength(4);
    // The growth raster is the canary: it was 1.3KB of white.
    for (const v of ["desktop", "mobile"]) {
      expect(statSync(join(PREVIEW_DIR, `growth-${v}.jpg`)).size).toBeGreaterThan(1800);
    }
  });

  it("centres the offer in the blurred chapter rather than sitting on top of it", () => {
    // MO, 2026-08-21: the paywall block should sit in the MIDDLE of each blurred
    // section. Measured at 1440 before this, the card sat 55-468px above the blurred
    // region's centre, the drift growing with the chapter's length. The card and the
    // raster share one grid cell, so `align-self` is the whole fix — and the cell is
    // the raster whenever the raster is the taller of the two.
    const css = readFileSync(join(process.cwd(), "app/globals.css"), "utf8");
    const at = css.indexOf("THE WHOLE CHAPTER SHOWS, NOT THE TOP OF IT");
    const block = css.slice(at, at + 9000);
    expect(block).toContain("align-self: center");
    expect(block).not.toContain("align-self: start;\n}");
    // Attachment locks in TWO boxes — the result card and the map article — and "the
    // middle" means the middle of the PAIR: half the card over each, centred on the
    // gap between them (MO, 2026-08-21). Centring on the two boxes' combined height
    // was arithmetically the middle but did not look like it: the map box is about
    // twice the result box, so the card sat almost entirely on the map.
    const root = css.slice(css.indexOf(".report-attachment--locked {"));
    const rootBody = root.slice(0, root.indexOf("}"));
    expect(rootBody).toContain("display: grid");
    // The grid area is the offer's containing block only if the grid is positioned...
    expect(rootBody).toContain("position: relative");
    // ...and the rows must be EXPLICIT: an absolutely positioned grid child cannot
    // reference implicit lines, and its area then falls back to the container's
    // padding box — which ends at the last box's bottom edge, so a wrong placement
    // still looked right until the offer needed a row's BOTTOM edge.
    expect(rootBody).toContain("grid-template-rows: auto auto");
    const rootWithPill = css.slice(
      css.indexOf(".report-attachment--locked:has(> .report-attachment__learn-pill-wrap) {")
    );
    expect(rootWithPill.slice(0, rootWithPill.indexOf("}"))).toContain(
      "grid-template-rows: auto auto auto"
    );
    // One source of truth for the gap, since the offer is centred on the middle of it.
    const attachRule = css.slice(css.indexOf(".report-attachment {"));
    expect(attachRule.slice(0, attachRule.indexOf("}"))).toContain(
      "--report-attach-gap: clamp(18px, 2.2vw, 27px)"
    );

    const overlayRule = css.slice(
      css.indexOf(".report-attachment--locked > .report-premium-overlay {")
    );
    const overlayBody = overlayRule.slice(0, overlayRule.indexOf("}"));
    // The result box's row: 1 without the "what you will learn" pill, 2 with it.
    expect(overlayBody).toContain("grid-row: 1 / 2");
    const withPill = css.slice(
      css.indexOf(
        ".report-attachment--locked:has(> .report-attachment__learn-pill-wrap) > .report-premium-overlay {"
      )
    );
    expect(withPill.slice(0, withPill.indexOf("}"))).toContain("grid-row: 2 / 3");
    // Hugging that row's bottom edge, shrunk to the card, so the translate is half the
    // CARD's height rather than half the box's.
    expect(overlayBody).toContain("top: auto");
    expect(overlayBody).toContain("bottom: 0");
    expect(overlayBody).toContain("height: max-content");
    // Half the card + half the gap = centred on the seam. It has to be written on the
    // OVERLAY: the card's own transform belongs to its reveal animation, and an
    // animated value beats a normal declaration, so the same rule on the card was
    // silently dropped (computed transform stayed the identity matrix).
    expect(overlayBody).toContain(
      "transform: translateY(calc(50% + var(--report-attach-gap) / 2))"
    );
    const cardRule = css.slice(
      css.indexOf(".report-attachment--locked > .report-premium-overlay > * {")
    );
    const cardBody = cardRule.slice(0, cardRule.indexOf("}"));
    expect(cardBody).toContain("pointer-events: auto");
    expect(cardBody).not.toContain("transform");
    // It must stay OUT of flow. An in-flow item placed on a row of a one-column grid
    // occupies that cell, so the boxes were auto-placed after it and the whole chapter
    // slid below the offer.
    expect(overlayBody).not.toContain("position: relative");
    expect(overlayBody).not.toContain("position: static");
    // Its empty area must not swallow clicks meant for what is under it.
    expect(overlayBody).toContain("pointer-events: none");

    // With the offer gone from the result box, the raster is back in flow and is what
    // gives that box its height — no absolute centring left behind.
    const rasterRule = css.slice(
      css.indexOf(".report-attachment__result-wrap--locked > .report-attachment__card-preview {")
    );
    const body = rasterRule.slice(0, rasterRule.indexOf("}"));
    expect(body).toContain("position: relative");
    expect(body).not.toContain("transform: translateY(-50%)");
  });

  it("keeps the confidence sub-headline out of the locked view", () => {
    // "Your Sexual Confidence" sat ABOVE the raster in both states, and the raster —
    // a capture of the paid card — contains its own blurred copy of that same line, so
    // a locked reader saw it twice: sharp, then blurred (MO, 2026-08-21, the last of
    // these). Every other chapter already renders its eyebrow in the paid arm only.
    const src = readFileSync(
      join(process.cwd(), "features/report/ui/sections/ConfidenceSection.tsx"),
      "utf8"
    );
    const card = src.slice(src.indexOf('<article className="report-confidence__card">'));
    const lockedArm = card.slice(card.indexOf("{locked ? ("), card.indexOf(") : ("));
    expect(lockedArm).toContain("LockedPreviewImage");
    expect(lockedArm).not.toContain("report-confidence__eyebrow");
    // ...and the paid arm still has it.
    expect(card.slice(card.indexOf(") : ("))).toContain(
      'report-confidence__eyebrow">Your Sexual Confidence'
    );
  });

  it("starts every reveal before capturing, wherever it sits in the card", () => {
    // `scrollIntoViewIfNeeded` only puts the section's TOP in view, and these cards run
    // 700-1200px, so anything lower never met its own IntersectionObserver and stayed at
    // `opacity: 0`. `settleReveal` then measured a perfectly stable HIDDEN element and
    // passed — the arousal raster shipped with a blank stat panel inside it (found
    // 2026-08-22; the same blank is in the previously committed file, so it was not a
    // regression). Adding the gate classes by hand starts the same transitions the
    // observer would, so the capture no longer depends on the viewport's height.
    const gen = readFileSync(join(process.cwd(), "scripts/generate-locked-previews.mjs"), "utf8");
    expect(gen).toContain("async function armReveals(");
    // every gate the report uses, or a chart stays hidden in its own way
    for (const gate of [
      '[".report-chart-reveal", "is-revealed"]',
      '[".report-part-reveal", "is-revealed"]',
      '[".report-attachment-plane", "is-revealed"]',
      '[".report-energy-graph", "is-revealed"]',
      '[".report-growth", "is-animated"]',
      '[".report-fantasy-map", "is-animated"]',
      '[".report-power-plane", "is-animated"]',
    ]) {
      expect(gen, gate).toContain(gate);
    }
    // armed BEFORE settling, in both capture paths, or the settle waits on nothing
    expect(
      gen.match(/await armReveals\(page, sectionId\);\n\s*await settleReveal\(/g)?.length
    ).toBe(2);
  });

  it("can regenerate one chapter instead of all 47 files", () => {
    // A one-chapter layout change used to mean re-encoding every raster and reading a
    // 47-line diff to find the two that mattered.
    const gen = readFileSync(join(process.cwd(), "scripts/generate-locked-previews.mjs"), "utf8");
    expect(gen).toContain("--only=");
    // both capture paths honour it, or a filtered run silently redoes half the set
    expect(gen).toContain("SECTION_IDS.filter(wanted)");
    expect(gen).toContain("COLUMN_CAPTURES.filter((c) => wanted(c.name) || wanted(c.sectionId))");
  });

  it("tones down anything that would survive the blur as a solid slab", () => {
    // A gaussian destroys text and thin lines, but a solid high-contrast slab just
    // becomes a soft dark blob — and a blob reads as a hard shape in an otherwise soft
    // image. Fantasy's active filter pill is `background: #161021`, so the top of that
    // locked chapter read "sharp" (MO, 2026-08-21).
    const gen = readFileSync(join(process.cwd(), "scripts/generate-locked-previews.mjs"), "utf8");
    expect(gen).toContain("SOFTEN_BEFORE_CAPTURE");
    expect(gen).toContain('".report-fantasy__filter.is-active"');
    // ...and it is put back afterwards, or the next capture on the same page inherits it.
    expect(gen).toContain("window.__previewSoftened");
  });

  it("renders every locked expander live, the gold three included", () => {
    // All sixteen chapters' expanders render live under the overlay and are blurred by
    // CSS — that is what makes them look alike. The three gold "practical" blocks used
    // to be gated on `hasPractical`, which is false on a locked report (the teaser and
    // the moves are the reader's own, withheld server-side), so they either vanished
    // or — captured into the raster instead — read at the raster's wash while every
    // other chapter's expander sat live beside it.
    for (const [file, slug] of [
      ["InsecuritiesSection.tsx", "insecurities"],
      ["InitiationSection.tsx", "initiation"],
      ["LibidoSection.tsx", "libido"],
    ]) {
      const src = readFileSync(join(SECTIONS_DIR, file), "utf8");
      expect(src, `${file} must render its expander when locked`).toContain(
        "{locked || hasPractical ? ("
      );
      // ...and the withheld teaser arrives as pixels in the same slot the universal
      // expanders fill with live text, so the block is not just a label and a button.
      expect(src).toContain(`<LockedPreviewImage name="practical-${slug}" />`);
    }
    // The capture takes the GLYPHS on flat white (the gold wash cleared) and the page
    // multiplies them onto the live wash. Baking the wash in left a visible rectangle
    // where the raster's slice of the gradient met the live one at a different phase,
    // so both halves have to stay in step.
    const gen = readFileSync(join(process.cwd(), "scripts/generate-locked-previews.mjs"), "utf8");
    expect(gen).toContain("clearBackdrop: true");
    expect(gen).toContain("quality: clearBackdrop ? 98 : 88");
    const css = readFileSync(join(process.cwd(), "app/globals.css"), "utf8");
    const at = css.indexOf(
      ".report-learn-peek > .report-locked-preview .report-locked-preview__img"
    );
    expect(at, "the shared peek-raster rule is gone").toBeGreaterThan(-1);
    expect(css.slice(at, css.indexOf("}", at))).toContain("mix-blend-mode: multiply");
    // No chapter keeps its expander inside a raster any more.
    expect(gen).not.toContain("KEEP_DETAILS_IN_RASTER");
  });

  it("renders no stand-in beside the raster", () => {
    // Both of these drew a second, live copy of content the raster already carries:
    // fantasy's category tables (771px) and the insecurities curve, which also drew a
    // DEFAULT cue family because the reader's own is withheld.
    const fantasy = readFileSync(join(SECTIONS_DIR, "FantasySection.tsx"), "utf8");
    expect(fantasy).not.toContain("report-fantasy__tables--locked");
    expect(fantasy).toContain("{tables && !locked ?");
    const ins = readFileSync(join(SECTIONS_DIR, "InsecuritiesSection.tsx"), "utf8");
    expect(ins).not.toContain("report-insecurities__graph-wrap--locked");
    // And the dead CSS went with them.
    const css = readFileSync(join(process.cwd(), "app/globals.css"), "utf8");
    expect(css).not.toContain("tables--locked");
    expect(css).not.toContain("graph-wrap--locked");
  });

  it.each(Object.entries(SECTIONS))("%s renders the preview image", (file, name) => {
    const src = readFileSync(join(SECTIONS_DIR, file), "utf8");
    expect(src).toContain(`<LockedPreviewImage name="${name}" />`);
  });

  it.each(Object.entries(SECTIONS))(
    "%s drops the CSS lock blur so the pixels are not blurred twice",
    (file, name) => {
      const src = readFileSync(join(SECTIONS_DIR, file), "utf8");
      expect(src).toContain(`report-${name}__preview-fade report-preview-fade--image`);
    }
  );

  it.each(Object.values(SECTIONS).flatMap((n) => [`${n}-desktop.jpg`, `${n}-mobile.jpg`]))(
    "%s exists and is not empty",
    (asset) => {
      const size = statSync(join(PREVIEW_DIR, asset)).size;
      // A blank white JPEG of this size compresses to well under 1KB; the real
      // captures are 1.5KB+. Catches a capture that rendered nothing.
      expect(size).toBeGreaterThan(1000);
    }
  );

  it("ships no preview asset that no section references", () => {
    const referenced = new Set(
      Object.values(SECTIONS).flatMap((n) => [`${n}-desktop.jpg`, `${n}-mobile.jpg`])
    );
    for (const name of COLUMN_PREVIEW_NAMES) {
      referenced.add(`${name}-desktop.jpg`);
      referenced.add(`${name}-mobile.jpg`);
    }
    const orphans = readdirSync(PREVIEW_DIR).filter(
      (f) => f.endsWith(".jpg") && !referenced.has(f)
    );
    expect(orphans, "unreferenced preview images — delete them or wire them up").toEqual([]);
  });

  it.each(Object.entries(COLUMN_PREVIEWS).flatMap(([file, names]) => names.map((n) => [file, n])))(
    "%s renders %s",
    (file, name) => {
      const src = readFileSync(join(SECTIONS_DIR, file), "utf8");
      expect(src).toContain(`<LockedPreviewImage name="${name}" />`);
    }
  );

  it.each(COLUMN_PREVIEW_NAMES.flatMap((n) => [`${n}-desktop.jpg`, `${n}-mobile.jpg`]))(
    "%s exists and is not empty",
    (asset) => {
      expect(statSync(join(PREVIEW_DIR, asset)).size).toBeGreaterThan(1000);
    }
  );
});
