import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Every locked premium section shows a pre-blurred render of its REAL chapter
 * behind the paywall overlay, generated by scripts/generate-locked-previews.mjs.
 *
 * Two things can silently break this and neither shows up in a type check:
 *  1. A section drifts back to stand-in DOM, or forgets the `--image` modifier
 *     and double-blurs the already-blurred pixels.
 *  2. An image file goes missing, which renders as an EMPTY box behind the
 *     paywall — the exact "there's nothing behind it" bug this replaced.
 *
 * Rendering all sixteen sections would need sixteen prop fixtures, so this
 * checks the source and the assets directly.
 *
 * BeliefsSection is deliberately NOT in this registry. Figma's locked frame for
 * that chapter does not blur it — it shows the real rows sharp at the top, fading
 * out toward the paywall card — so it teases server-trimmed copy instead of a
 * raster. See BeliefsSection.locked.test.tsx. Its generated images are therefore
 * unreferenced, which the orphan check below allows for by name.
 */
const SECTIONS_DIR = join(process.cwd(), "features/report/ui/sections");
const PREVIEW_DIR = join(process.cwd(), "public/report-previews");

/** section component file -> preview asset name */
const SECTIONS: Record<string, string> = {
  "AcceleratorsSection.tsx": "accel",
  "ArousalSection.tsx": "arousal",
  "ConfidenceSection.tsx": "confidence",
  "CuriositySection.tsx": "curiosity",
  "EnergySection.tsx": "energy",
  "FantasySection.tsx": "fantasy",
  "GrowthSection.tsx": "growth",
  "InitiationSection.tsx": "initiation",
  "InsecuritiesSection.tsx": "insecurities",
  "LibidoSection.tsx": "libido",
  "LoveLanguageSection.tsx": "lovelang",
  "PartnershipSection.tsx": "partnership",
  "PowerSection.tsx": "power",
  "ReadingSection.tsx": "reading",
  "RewardSection.tsx": "reward",
};

describe("locked preview images", () => {
  it.each(Object.entries(SECTIONS))("%s renders the preview image", (file, name) => {
    const src = readFileSync(join(SECTIONS_DIR, file), "utf8");
    expect(src).toContain(`<LockedPreviewImage name="${name}" />`);
  });

  it.each(Object.entries(SECTIONS))(
    "%s drops the CSS lock blur so the pixels are not blurred twice",
    (file, name) => {
      const src = readFileSync(join(SECTIONS_DIR, file), "utf8");
      expect(src).toContain(`report-${name}__preview-fade report-preview-fade--image`);
    }
  );

  it.each(Object.values(SECTIONS).flatMap((n) => [`${n}-desktop.jpg`, `${n}-mobile.jpg`]))(
    "%s exists and is not empty",
    (asset) => {
      const size = statSync(join(PREVIEW_DIR, asset)).size;
      // A blank white JPEG of this size compresses to well under 1KB; the real
      // captures are 1.5KB+. Catches a capture that rendered nothing.
      expect(size).toBeGreaterThan(1000);
    }
  );

  it("ships no preview asset that no section references", () => {
    const referenced = new Set(
      Object.values(SECTIONS).flatMap((n) => [`${n}-desktop.jpg`, `${n}-mobile.jpg`])
    );
    // Beliefs switched to a copy-based tease; its rasters stay on disk so the
    // generator's section list and the wiring can diverge without failing here.
    referenced.add("beliefs-desktop.jpg");
    referenced.add("beliefs-mobile.jpg");
    const orphans = readdirSync(PREVIEW_DIR).filter(
      (f) => f.endsWith(".jpg") && !referenced.has(f)
    );
    expect(orphans, "unreferenced preview images — delete them or wire them up").toEqual([]);
  });
});
