-- Auto-generated by scripts/_gen-resync.js — V3 DB content re-sync.
-- Syncs survey_question.question + answer_option.option_text to the
-- canonical client source (data/survey-data.ts) after the 2026-05-19 V3
-- refresh shipped to the app but never to the DB (drift → lost multi-select
-- answers, unlinked single answers). Positional by display_order.
-- Q14020 + Q16011 (option-count changed in V3) are hand-mapped below.

BEGIN;

-- 00000 (open)
UPDATE survey_question SET question = 'What is your email?', updated_date_time = now() WHERE frontend_qid = '00000';

-- 00001 (open)
UPDATE survey_question SET question = 'What is your name?', updated_date_time = now() WHERE frontend_qid = '00001';

-- 01002 (scale)
UPDATE survey_question SET question = 'Right now, I feel satisfied with my sex life.', updated_date_time = now() WHERE frontend_qid = '01002';

-- 01005 (scale)
UPDATE survey_question SET question = 'I want more variety — new positions, places, fantasies, or kinds of sex.', updated_date_time = now() WHERE frontend_qid = '01005';

-- 01006 (scale)
UPDATE survey_question SET question = 'Sex often hurts or feels physically bad for me.', updated_date_time = now() WHERE frontend_qid = '01006';

-- 02001 (single)
UPDATE survey_question SET question = 'When you wanted sex recently, what usually happened first?', updated_date_time = now() WHERE frontend_qid = '02001';
UPDATE answer_option ao SET option_text = 'Nothing — I just got horny on my own' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '02001' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Something happened first: touch, flirting, kissing, fantasy, closeness' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '02001' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Sex was planned, with time and privacy set aside' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '02001' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'It depends — varies by person or situation' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '02001' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'I haven''t felt much desire lately' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '02001' AND ao.display_order = 5;

-- 02002 (scale)
UPDATE survey_question SET question = 'My desire only kicks in after touch, kissing, or feeling close — it rarely shows up out of nowhere.', updated_date_time = now() WHERE frontend_qid = '02002';

-- 02003 (scale)
UPDATE survey_question SET question = 'I enjoy sex more when it''s planned ahead than when it just happens.', updated_date_time = now() WHERE frontend_qid = '02003';

-- 02004 (single)
UPDATE survey_question SET question = 'What kind of starting point usually leads to the best sex for you?', updated_date_time = now() WHERE frontend_qid = '02004';
UPDATE answer_option ao SET option_text = 'I''m the one who starts things — I make the first move' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '02004' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'The other person starts things — I respond to them' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '02004' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'It works best when we plan it ahead and both know it''s coming' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '02004' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'It happens naturally, with no one having to start' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '02004' AND ao.display_order = 4;

-- 03003 (multiple)
UPDATE survey_question SET question = 'Which kinds of settings or vibes most reliably turn you on?', updated_date_time = now() WHERE frontend_qid = '03003';
UPDATE answer_option ao SET option_text = 'Private, calm, and feeling safe' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03003' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'New or adventurous situations' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03003' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Slow, intentional, almost ritual-like' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03003' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Unplanned, spur-of-the-moment' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03003' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'A bit forbidden, edgy, or rule-breaking' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03003' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'Being seen — or almost being seen — by others' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03003' AND ao.display_order = 6;
UPDATE answer_option ao SET option_text = 'Something else' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03003' AND ao.display_order = 7;

-- 03004 (scale)
UPDATE survey_question SET question = 'I need to feel emotionally close before I want sex.', updated_date_time = now() WHERE frontend_qid = '03004';

-- 03005 (single)
UPDATE survey_question SET question = 'What most reliably moves you from ''not really interested'' to actually turned on?', updated_date_time = now() WHERE frontend_qid = '03005';
UPDATE answer_option ao SET option_text = 'Physical stuff — touch, rhythm, build-up, body sensation' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03005' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'The right setting — low stress, privacy, time, feeling safe' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03005' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Emotional closeness — warmth, affection, feeling connected' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03005' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Something new — surprise, exploration, novelty' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03005' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Skill and technique — when one of us is really good at it' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03005' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'My imagination — fantasy, what I''m watching, reading, or picturing' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03005' AND ao.display_order = 6;
UPDATE answer_option ao SET option_text = 'It varies — no single thing stands out' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03005' AND ao.display_order = 7;

-- 03006 (single)
UPDATE survey_question SET question = 'How do you usually figure out what works for you sexually?', updated_date_time = now() WHERE frontend_qid = '03006';
UPDATE answer_option ao SET option_text = 'I want clear guidance, instructions, and feedback' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03006' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'I learn by trying things and seeing what happens' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03006' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'I follow what feels natural in the moment, no overthinking' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03006' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'I''d rather not treat sex as a project to work on' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03006' AND ao.display_order = 4;

-- 03008 (scale)
UPDATE survey_question SET question = 'I prefer sex that is intense and high-energy over sex that is soft and slow.', updated_date_time = now() WHERE frontend_qid = '03008';

-- 03009 (scale)
UPDATE survey_question SET question = 'Sexual tension, anticipation, and being chased or pursued reliably turn me on.', updated_date_time = now() WHERE frontend_qid = '03009';

-- 03010 (single)
UPDATE survey_question SET question = 'Which kind of sexual atmosphere usually feels best for you?', updated_date_time = now() WHERE frontend_qid = '03010';
UPDATE answer_option ao SET option_text = 'Very safe, calm, and predictable' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03010' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Mostly safe, with a little novelty' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03010' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'A balance of familiar and new' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03010' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Adventurous, as long as the limits are clear' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03010' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Intense or taboo energy — within limits we''ve both agreed to.' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03010' AND ao.display_order = 5;

-- 03011 (scale)
UPDATE survey_question SET question = 'Sex feels best to me when it feels meaningful or sacred — not just physical.', updated_date_time = now() WHERE frontend_qid = '03011';

-- 03012 (scale)
UPDATE survey_question SET question = 'Without something a bit forbidden, taboo, or high-intensity, sex can feel flat to me.', updated_date_time = now() WHERE frontend_qid = '03012';

-- 03013 (single)
UPDATE survey_question SET question = 'Which turns you on most?', updated_date_time = now() WHERE frontend_qid = '03013';
UPDATE answer_option ao SET option_text = 'Being watched, desired, or admired' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03013' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Watching the other person — their body, reactions, pleasure' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03013' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Getting fully absorbed in the feeling, with no focus on watching either way' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03013' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Not sure' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '03013' AND ao.display_order = 4;

-- 03014 (scale)
UPDATE survey_question SET question = 'During sex, I can usually reach orgasm when I want to.', updated_date_time = now() WHERE frontend_qid = '03014';

-- 08002 (scale)
UPDATE survey_question SET question = 'I generally feel secure in my close relationships.', updated_date_time = now() WHERE frontend_qid = '08002';

-- 08003 (single)
UPDATE survey_question SET question = 'When someone you feel close to pulls away or goes cold, you usually…', updated_date_time = now() WHERE frontend_qid = '08003';
UPDATE answer_option ao SET option_text = 'Move toward them, looking for reassurance or contact' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '08003' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Pull back, go quiet, or create distance yourself' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '08003' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Get frustrated, irritated, or push back at them' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '08003' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Stay calm and handle it on your own' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '08003' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'It depends on the person or situation' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '08003' AND ao.display_order = 5;

-- 08004 (scale)
UPDATE survey_question SET question = 'I usually want more closeness and togetherness than space and independence.', updated_date_time = now() WHERE frontend_qid = '08004';

-- 08005 (scale)
UPDATE survey_question SET question = 'After a real make-up talk where we both opened up, I often want them sexually.', updated_date_time = now() WHERE frontend_qid = '08005';

-- 08006 (scale)
UPDATE survey_question SET question = 'When I feel pressure during sex — to perform, to talk, or to take it further — I tend to shut down or want to pull away.', updated_date_time = now() WHERE frontend_qid = '08006';

-- 08012 (scale)
UPDATE survey_question SET question = 'I lose interest in sex when the other person leans on me too much emotionally.', updated_date_time = now() WHERE frontend_qid = '08012';

-- 09013 (scale)
UPDATE survey_question SET question = 'I sometimes use flirting or sex to calm tension, get reassurance, or avoid asking for what I need directly.', updated_date_time = now() WHERE frontend_qid = '09013';

-- 10002 (multiple)
UPDATE survey_question SET question = 'During sex, how do you most naturally show or say what you want?', updated_date_time = now() WHERE frontend_qid = '10002';
UPDATE answer_option ao SET option_text = 'Through touch — guiding hands, moving their body, using my own body' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '10002' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'With short, direct words ("more", "harder", "slower", "yes")' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '10002' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Talking and giving feedback throughout' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '10002' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Checking in emotionally — asking how they feel, sharing how I feel' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '10002' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Mostly through sounds, looks, and body language' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '10002' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'I don''t communicate much during sex' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '10002' AND ao.display_order = 6;

-- 10003 (scale)
UPDATE survey_question SET question = 'I''m comfortable expressing what turns me on.', updated_date_time = now() WHERE frontend_qid = '10003';

-- 10004 (scale)
UPDATE survey_question SET question = 'I''m comfortable saying what I don''t want — slowing things down, stopping, or naming a limit.', updated_date_time = now() WHERE frontend_qid = '10004';

-- 10005 (scale)
UPDATE survey_question SET question = 'If the other person is quiet or hard to read during sex, I lose arousal.', updated_date_time = now() WHERE frontend_qid = '10005';

-- 11001 (single)
UPDATE survey_question SET question = 'Which power dynamic most naturally turns you on?', updated_date_time = now() WHERE frontend_qid = '11001';
UPDATE answer_option ao SET option_text = 'Being the one in charge — leading, directing, setting the pace' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '11001' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Letting the other person take charge — following, surrendering, being led' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '11001' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Switching — sometimes leading, sometimes letting go' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '11001' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Equal — we meet in the middle, no one''s in charge' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '11001' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Not sure / depends on the situation' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '11001' AND ao.display_order = 5;

-- 11002 (scale)
UPDATE survey_question SET question = 'I enjoy clear roles, agreements, or rules during sex.', updated_date_time = now() WHERE frontend_qid = '11002';

-- 11003 (scale)
UPDATE survey_question SET question = 'During sex, I focus more on the other person''s pleasure than on my own.', updated_date_time = now() WHERE frontend_qid = '11003';

-- 11004 (scale)
UPDATE survey_question SET question = 'Taking care of someone — being attentive, soothing, healing — turns me on.', updated_date_time = now() WHERE frontend_qid = '11004';

-- 14020 (multiple)
UPDATE survey_question SET question = 'What most reliably makes you actually want sex?', updated_date_time = now() WHERE frontend_qid = '14020';
-- 14020 options: V3 dropped 2 of 11 (DB order 10 "Healing and soothing",
-- 11 "Escape and relief"). Map the surviving 9 by concept (display_order shown):
--   1 Bonding and closeness        -> Feeling emotionally close to the other person
--   2 Pleasure and play            -> Fun and play — pleasure for its own sake
--   3 Novelty and discovery        -> Trying something new or unfamiliar
--   4 Intensity and edge           -> Strong charge, tension, or edge
--   5 Feeling desired              -> Feeling wanted, desired, or chosen
--   6 Power and polarity           -> A clear lead/follow dynamic between us
--   7 Meaning and devotion         -> Meaning, depth, or devotion
--   8 Comfort and familiarity      -> Comfort, soothing, or stress relief
--   9 Giving and service           -> Pleasing or taking care of the other person
-- DB order 10 & 11 are left as-is (V3 no longer offers them; the client never
-- sends them, so they stay only for pre-V3 historical answers).
UPDATE answer_option ao SET option_text = 'Feeling emotionally close to the other person' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '14020' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Fun and play — pleasure for its own sake' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '14020' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Trying something new or unfamiliar' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '14020' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Strong charge, tension, or edge' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '14020' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Feeling wanted, desired, or chosen' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '14020' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'A clear lead/follow dynamic between us' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '14020' AND ao.display_order = 6;
UPDATE answer_option ao SET option_text = 'Meaning, depth, or devotion' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '14020' AND ao.display_order = 7;
UPDATE answer_option ao SET option_text = 'Comfort, soothing, or stress relief' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '14020' AND ao.display_order = 8;
UPDATE answer_option ao SET option_text = 'Pleasing or taking care of the other person' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '14020' AND ao.display_order = 9;

-- 14021 (scale)
UPDATE survey_question SET question = 'I sometimes go for intense sex to snap out of feeling stressed, flat, or shut down.', updated_date_time = now() WHERE frontend_qid = '14021';

-- 15001 (country)
UPDATE survey_question SET question = 'Which country do you live in?', updated_date_time = now() WHERE frontend_qid = '15001';

-- 15002 (open)
UPDATE survey_question SET question = 'Which ZIP / postal code do you live in?', updated_date_time = now() WHERE frontend_qid = '15002';

-- 15003 (single)
UPDATE survey_question SET question = 'Which age range are you in?', updated_date_time = now() WHERE frontend_qid = '15003';
UPDATE answer_option ao SET option_text = '18–24' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15003' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = '25–34' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15003' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = '35–44' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15003' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = '45–54' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15003' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = '55–64' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15003' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = '65+' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15003' AND ao.display_order = 6;

-- 15004 (single)
UPDATE survey_question SET question = 'What kind of relationship setup are you in right now?', updated_date_time = now() WHERE frontend_qid = '15004';
UPDATE answer_option ao SET option_text = 'Single' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15004' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'In one exclusive relationship (only each other)' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15004' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Mostly exclusive, with some agreed exceptions' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15004' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Non-exclusive, with agreed limits — known as ''open''' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15004' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Multiple committed relationships, with everyone''s knowledge — known as ''polyamorous''' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15004' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'Multiple connections, prioritizing my own independence (no shared household)' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15004' AND ao.display_order = 6;
UPDATE answer_option ao SET option_text = 'Still figuring it out / doesn''t fit a label' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15004' AND ao.display_order = 7;

-- 15005 (single)
UPDATE survey_question SET question = 'Do you have children?', updated_date_time = now() WHERE frontend_qid = '15005';
UPDATE answer_option ao SET option_text = 'No' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15005' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Yes, youngest is 0–3' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15005' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Yes, youngest is 4–10' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15005' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Yes, youngest is 11–17' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15005' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Yes, children are 18+ and live with me' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15005' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'Yes, children are 18+ and do not live with me' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15005' AND ao.display_order = 6;
UPDATE answer_option ao SET option_text = 'Prefer not to answer' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15005' AND ao.display_order = 7;

-- 15006 (single)
UPDATE survey_question SET question = 'How high is your overall stress level most of the time?', updated_date_time = now() WHERE frontend_qid = '15006';
UPDATE answer_option ao SET option_text = 'Very low' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15006' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Low' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15006' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Medium' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15006' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'High' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15006' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Very high' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15006' AND ao.display_order = 5;

-- 15007 (single)
UPDATE survey_question SET question = 'How rested do you usually feel when you wake up?', updated_date_time = now() WHERE frontend_qid = '15007';
UPDATE answer_option ao SET option_text = 'Very rested' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15007' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Rather rested' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15007' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'In between' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15007' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Rather tired' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15007' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Very tired' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15007' AND ao.display_order = 5;

-- 15008 (single)
UPDATE survey_question SET question = 'Do you live with any long-term physical or mental health conditions that affect your energy, mood, or everyday functioning?', updated_date_time = now() WHERE frontend_qid = '15008';
UPDATE answer_option ao SET option_text = 'No' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15008' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Yes, mainly physical health' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15008' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Yes, mainly mental health' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15008' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Yes, both physical and mental health' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15008' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'I''m not sure' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15008' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'Prefer not to answer' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15008' AND ao.display_order = 6;

-- 15009 (single)
UPDATE survey_question SET question = 'Are you currently taking any medication or hormones that you think might affect your energy, mood, or sex drive?', updated_date_time = now() WHERE frontend_qid = '15009';
UPDATE answer_option ao SET option_text = 'No' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15009' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Yes, lowers my drive' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15009' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Yes, increases my drive' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15009' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Yes, not sure how it affects me' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15009' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Prefer not to answer' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15009' AND ao.display_order = 5;

-- 15010 (single)
UPDATE survey_question SET question = 'What is your gender identity?', updated_date_time = now() WHERE frontend_qid = '15010';
UPDATE answer_option ao SET option_text = 'Woman' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15010' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Man' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15010' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Nonbinary' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15010' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Other' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15010' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'I''d rather not label this' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15010' AND ao.display_order = 5;

-- 15011 (single)
UPDATE survey_question SET question = 'What is your sexual orientation?', updated_date_time = now() WHERE frontend_qid = '15011';
UPDATE answer_option ao SET option_text = 'Heterosexual' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15011' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Homosexual' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15011' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Bisexual' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15011' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Pansexual' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15011' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Queer' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15011' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'Questioning / exploring' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15011' AND ao.display_order = 6;
UPDATE answer_option ao SET option_text = 'Other' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15011' AND ao.display_order = 7;
UPDATE answer_option ao SET option_text = 'I don''t use a label' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '15011' AND ao.display_order = 8;

-- 16001 (multiple)
UPDATE survey_question SET question = 'Which changes would actually improve your sex life over the next 3 months?', updated_date_time = now() WHERE frontend_qid = '16001';
UPDATE answer_option ao SET option_text = 'Wanting sex more often — more drive, easier to get turned on' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'More pleasure or easier orgasms' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Less pain or physical discomfort during sex' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Feeling more emotionally close during sex' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Talking more openly about what I want and don''t want' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'More excitement, freshness, or playfulness' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 6;
UPDATE answer_option ao SET option_text = 'Feeling more confident in my own body' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 7;
UPDATE answer_option ao SET option_text = 'Feeling more connected to my own sexuality' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 8;
UPDATE answer_option ao SET option_text = 'Healing past experiences that still affect me sexually' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 9;
UPDATE answer_option ao SET option_text = 'Being more on the same page with someone I''m involved with' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 10;
UPDATE answer_option ao SET option_text = 'Something else' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16001' AND ao.display_order = 11;

-- 16002 (scale)
UPDATE survey_question SET question = 'Working on my sexuality is a priority for me right now.', updated_date_time = now() WHERE frontend_qid = '16002';

-- 16005 (single)
UPDATE survey_question SET question = 'Which of these best describes where your sexuality feels right now?', updated_date_time = now() WHERE frontend_qid = '16005';
UPDATE answer_option ao SET option_text = 'Pausing — I need a break from sex right now' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16005' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Repairing — I''m working to feel safe and close again after something hurt' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16005' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Waking up — I''m figuring out what I actually enjoy' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16005' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Experimenting — I''m ready to try new things and have more fun' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16005' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Steady — Sex feels normal and good in my life' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16005' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'Transcending — Sex feels connected to something bigger than just pleasure' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16005' AND ao.display_order = 6;

-- 16006 (single)
UPDATE survey_question SET question = 'Where would you like your sexuality to be 3–6 months from now?', updated_date_time = now() WHERE frontend_qid = '16006';
UPDATE answer_option ao SET option_text = 'More rest and space from sex right now' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16006' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Rebuilding trust and safety in my sexuality' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16006' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Rediscover what turns me on and what I enjoy' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16006' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Explore more, try new things, and feel more confident' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16006' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'I want sex to feel natural and integrated into my everyday life' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16006' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'I want sex to feel spiritually meaningful and deeply connected' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16006' AND ao.display_order = 6;

-- 16007 (single)
UPDATE survey_question SET question = 'When you want to improve something important in your life (health, relationships, confidence), what''s usually your first move?', updated_date_time = now() WHERE frontend_qid = '16007';
UPDATE answer_option ao SET option_text = 'Read, watch, or listen on my own' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16007' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Use a tool — an app, journal, or worksheet' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16007' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Sign up for a program or course' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16007' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Work with a professional (therapist, coach, etc.)' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16007' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'I usually only act once it becomes urgent' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16007' AND ao.display_order = 5;

-- 16008 (multiple)
UPDATE survey_question SET question = 'What kind of support would actually help you most with your top focus?', updated_date_time = now() WHERE frontend_qid = '16008';
UPDATE answer_option ao SET option_text = 'Self-guided tools I can use on my own (prompts, exercises, reflections)' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16008' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'A short, structured program over a few weeks' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16008' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'A live group, workshop, or circle' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16008' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Support I can do together with the person I''m with' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16008' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = '1-on-1 work with a professional' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16008' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'Not sure yet' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16008' AND ao.display_order = 6;

-- 16011 (multiple)
UPDATE survey_question SET question = 'Which of these are already part of your life?', updated_date_time = now() WHERE frontend_qid = '16011';
-- 16011 options: V3 dropped 1 of 7 (DB order 6 "Other"). Map the surviving 6:
--   1 Therapy, coaching, or counseling     -> (unchanged)
--   2 Books or long-form reading           -> Books or other long reads
--   3 Apps for wellbeing or self-regulation-> Apps for things like meditation, sleep, or breathwork
--   4 Digital content subscriptions        -> Paid subscriptions (streaming, podcasts, lifestyle apps)
--   5 Courses, programs, or memberships    -> Online courses, programs, or paid communities
--   7 None of these                        -> (unchanged)
-- DB order 6 "Other" left as-is (V3 dropped it; client never sends it).
UPDATE answer_option ao SET option_text = 'Therapy, coaching, or counseling' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16011' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'Books or other long reads' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16011' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'Apps for things like meditation, sleep, or breathwork' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16011' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'Paid subscriptions (streaming, podcasts, lifestyle apps)' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16011' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Online courses, programs, or paid communities' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16011' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'None of these' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16011' AND ao.display_order = 7;

-- 16012 (single)
UPDATE survey_question SET question = 'Roughly how much do you spend per year on personal growth — books, courses, therapy, coaching, apps?', updated_date_time = now() WHERE frontend_qid = '16012';
UPDATE answer_option ao SET option_text = '€0' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16012' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = '€1–99' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16012' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = '€100–299' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16012' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = '€300–699' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16012' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = '€700–1,499' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16012' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = '€1,500+' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16012' AND ao.display_order = 6;

-- 16013 (scale)
UPDATE survey_question SET question = 'Understanding my sexuality is important to me.', updated_date_time = now() WHERE frontend_qid = '16013';

-- 16014 (multiple)
UPDATE survey_question SET question = 'What''s actually getting in the way of improving your sexuality right now?', updated_date_time = now() WHERE frontend_qid = '16014';
UPDATE answer_option ao SET option_text = 'I''m not sure what would actually help' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16014' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'I don''t have enough time or energy' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16014' AND ao.display_order = 2;
UPDATE answer_option ao SET option_text = 'The person I''m with isn''t on the same page or willing to engage' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16014' AND ao.display_order = 3;
UPDATE answer_option ao SET option_text = 'It doesn''t feel emotionally safe enough yet' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16014' AND ao.display_order = 4;
UPDATE answer_option ao SET option_text = 'Shame, self-judgment, or inner pressure' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16014' AND ao.display_order = 5;
UPDATE answer_option ao SET option_text = 'Physical pain or body issues' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16014' AND ao.display_order = 6;
UPDATE answer_option ao SET option_text = 'Useful support feels too expensive or hard to access' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16014' AND ao.display_order = 7;
UPDATE answer_option ao SET option_text = 'I struggle to keep going with things over time' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16014' AND ao.display_order = 8;
UPDATE answer_option ao SET option_text = 'Nothing major is in the way right now' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16014' AND ao.display_order = 9;
UPDATE answer_option ao SET option_text = 'Something else' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16014' AND ao.display_order = 10;

-- 16015 (single)
UPDATE survey_question SET question = 'Would you like to receive free LoveIQ hints and insights?', updated_date_time = now() WHERE frontend_qid = '16015';
UPDATE answer_option ao SET option_text = 'Yes, I want to keep learning about myself.' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16015' AND ao.display_order = 1;
UPDATE answer_option ao SET option_text = 'No, I am not interested in this growth opportunity.' FROM survey_question sq WHERE ao.survey_question_id = sq.id AND sq.frontend_qid = '16015' AND ao.display_order = 2;

COMMIT;
