create table if not exists public.admin_investigation_case (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  status text not null default 'needs-review' check (status in ('needs-review', 'root-cause-found', 'question-change-candidate', 'monitoring', 'closed')),
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  owner_email text,
  due_date date,
  submission_id bigint references public.survey_submission(id) on delete set null,
  segment_id bigint references public.admin_segment(id) on delete set null,
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists admin_investigation_case_status_idx on public.admin_investigation_case(status);
create index if not exists admin_investigation_case_owner_idx on public.admin_investigation_case(owner_email);
create index if not exists admin_investigation_case_due_date_idx on public.admin_investigation_case(due_date);
create index if not exists admin_investigation_case_submission_idx on public.admin_investigation_case(submission_id);
create index if not exists admin_investigation_case_segment_idx on public.admin_investigation_case(segment_id);;
