-- Auto-generated by scripts/generate-seed-sql.js — do not edit manually
-- Run: node scripts/generate-seed-sql.js > supabase/migrations/20260307100001_seed_survey_data.sql

BEGIN;

-- ─── Survey ─────────────────────────────────────────────────────────────────
INSERT INTO survey (title, description, language, estimated_duration_min, status)
VALUES ('LoveIQ Survey', 'The LoveIQ personal sexuality & relationship survey', 'en', 20, 'active');

-- Capture the survey id
DO $$
DECLARE
  v_survey_id BIGINT;
  v_q_id BIGINT;
BEGIN
  SELECT id INTO v_survey_id FROM survey WHERE title = 'LoveIQ Survey' AND status = 'active' LIMIT 1;

  -- ─── Questions, Options & Mappings ──────────────────────────────────────────

  -- Q1: 00000 (open)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('open', 'What is your email?', 'Use an email you check regularly and can access on this device. Double-check spelling (no spaces). If you’re using a work email that filters messages, consider a personal one so you don’t miss your report or login link. Examples: max@example.com; nikola@example.com; banana.bandit@example.com', 1, true, '00000', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q2: 00001 (open)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('open', 'What is your first name?', 'Enter the name you’d like to be addressed by in your results (it can be a nickname). Keep it short and recognizable so your report feels personal. Examples: Max; NikolaT; Banana Bandit', 2, true, '00001', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q3: 01002 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'Overall, how satisfied are you with your sex life right now?', 'Think about the last 4–8 weeks overall. Include both quality and frequency, plus how aligned it feels with what you want. Try to rate your real experience (not what you think “should” be true). If you’re currently not sexually active, rate your satisfaction with how things are for you right now.', 3, true, '01002', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q4: 01003 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Which statement best describes your relationship with sexuality right now?', 'Choose the biggest factor right now. If a few apply, pick the one that’s most responsible.', 4, true, '01003', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'It’s genuinely not a priority for me (stable preference)', 'It’s genuinely not a priority for me (stable preference)', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'It’s temporarily deprioritized (stress / life load)', 'It’s temporarily deprioritized (stress / life load)', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'It feels complicated (pain, shame, resentment, disconnection)', 'It feels complicated (pain, shame, resentment, disconnection)', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I’m not sure', 'I’m not sure', 4);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q5: 01005 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I often crave more novelty/variety in my sexual experiences.', '“Novelty/variety” can mean new activities, new scenarios, different pacing, different locations, new fantasies, or simply changing routines. Answer for your usual pattern: do you regularly feel a pull toward “something different,” even if you don’t act on it?', 5, true, '01005', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q6: 01006 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'Sex is often uncomfortable or painful for me.', 'Answer based on your typical experience over the past few months. “Sex” here includes any sexual activity you engage in (not only penetration). If pain happens only in specific situations (certain positions, dryness, anxiety, condoms, toys, certain timing in your cycle), still factor that in when choosing your rating.', 6, true, '01006', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q7: 02001 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Which is most true for you?', 'Pick the option that fits you most of the time in your current life (last 3–6 months). “Spontaneous” means desire appears before touch/attention. “Responsive” means desire often shows up after flirting, touch, closeness, or erotic cues. “Planned window” means you do best when you intentionally set aside time and let things build. If it truly depends heavily on partner/context, choose that. If desire has been noticeably low lately compared to your usual baseline, choose “low lately.”', 7, true, '02001', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I often feel desire spontaneously (it starts inside me)', 'I often feel desire spontaneously (it starts inside me)', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I usually warm up after affectionate/erotic cues (responsive)', 'I usually warm up after affectionate/erotic cues (responsive)', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I need a planned ‘window’ to get into it', 'I need a planned ‘window’ to get into it', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'It varies a lot by partner/context', 'It varies a lot by partner/context', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Desire has been low lately', 'Desire has been low lately', 5);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q8: 02002 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I usually don’t feel sexual desire until someone shows me affection or starts something intimate.', '“Affectionate or erotic cues” can be kissing, cuddling, feeling emotionally close, flirting, erotic talk, touch, a date night vibe, or seeing your partner in a sexy context. Rate how often this is true for you generally, not just with a specific partner on a specific day.', 8, true, '02002', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q9: 02003 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I enjoy intimacy more when it’s planned rather than spontaneous.', '“Planned time” means intentionally setting a window (even loosely) where intimacy could happen. “Spur-of-the-moment” means unplanned initiation in everyday life. Answer based on what reliably leads to enjoyable sex for you (less pressure, easier arousal, better experience), not what sounds most romantic.', 9, true, '02003', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q10: 02004 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'In a good scenario, initiation feels best when…', 'Choose the scenario that most often creates your best, most relaxed, most turned-on experience. This is about what works (emotionally and physically), not about fairness or what you wish were true. If multiple feel true, pick the one that has the highest success rate.', 10, true, '02004', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I start it', 'I start it', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'My partner starts and I warm up', 'My partner starts and I warm up', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'We plan a window and see what happens', 'We plan a window and see what happens', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Either of us, in a playful moment', 'Either of us, in a playful moment', 4);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q11: 03003 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'What is your preferred setting of sexual connection?', 'Answer for your ideal setting when you can choose freely. “Private” = safe, closed-door, low chance of interruption. “Adventurous” = different locations or a sense of exploring. “Ritualized” = a familiar setup/sequence (music, lighting, routine) that helps you drop in. “Spontaneous” = unplanned, in-the-moment. “Public risk” = the thrill of being noticed or almost caught (without breaking consent or laws). Choose “Other” if your preference is something like nature, travel, mornings-only, etc.', 11, true, '03003', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Private', 'Private', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Adventurous', 'Adventurous', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Ritualized', 'Ritualized', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Spontaneous', 'Spontaneous', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Public risk', 'Public risk', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Other (please specify)', 'Other (please specify)', 6);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q12: 03004 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'How essential is emotional connection for your sexual desire?', '“Emotional connection” means feeling safe, cared for, understood, and emotionally close. Rate how necessary that feeling is for your desire to show up with a partner. This is not about whether you can physically get aroused, but whether you genuinely want sex and enjoy it.', 12, true, '03004', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q13: 03005 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Which description best fits what gets you from neutral to turned-on most often?', 'Pick the main “on switch” that most reliably moves you from neutral to aroused. “Sensation-led” = touch, rhythm, teasing, physical buildup. “Safety/context-led” = privacy, low stress, time, no interruptions. “Connection-led” = warmth, affection, emotional closeness. “Novelty/adventure-led” = new ideas, new settings, toys, experimentation. “Mastery/competence-led” = skill, technique, getting better together, learning what works. “Fantasy/imagination-led” = mental imagery, role play, erotica, audio/visual cues. Choose “varies” if there is no consistent pattern.', 13, true, '03005', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Sensation-led (touch/tempo/teasing)', 'Sensation-led (touch/tempo/teasing)', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Safety/context-led (privacy, low stress, no interruptions)', 'Safety/context-led (privacy, low stress, no interruptions)', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Connection-led (warmth, affection, closeness)', 'Connection-led (warmth, affection, closeness)', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Novelty/adventure-led (new ideas, toys, new settings)', 'Novelty/adventure-led (new ideas, toys, new settings)', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Mastery/competence-led (technique, skill-building)', 'Mastery/competence-led (technique, skill-building)', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Fantasy/imagination-led (role-play, mental imagery, erotica/audio/visual)', 'Fantasy/imagination-led (role-play, mental imagery, erotica/audio/visual)', 6);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Not sure / varies a lot', 'Not sure / varies a lot', 7);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q14: 03006 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Which "learning mode" best fits you?', '“Learning mode” means treating sex partly like exploration or skill-building. “Taught/guided” = you enjoy instruction, demonstration, or step-by-step guidance in the moment. “Optimizing/system” = you like understanding patterns, feedback, and what works (like experimenting and refining). “Don’t want learning mode” = you prefer it to feel natural/instinctive in the moment and not like a lesson. Pick what feels most comfortable, not what you think is most mature.', 14, true, '03006', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '“I like being taught/guided step-by-step.”', '“I like being taught/guided step-by-step.”', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '“I like optimizing/understanding the system.”', '“I like optimizing/understanding the system.”', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '“I don’t want ‘learning mode’ during sex.”', '“I don’t want ‘learning mode’ during sex.”', 3);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q15: 03008 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I usually want sex to feel...', '“Calm and nourishing” means gentle, soothing, connected, regulated. “Charged and intense” means high energy, strong build, urgency, edge, heat. Rate your preferred emotional/physical intensity level most of the time.', 15, true, '03008', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q16: 03009 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'Tension, pursuit, or being ‘hard to get’ reliably turns me on.', '“Tension/pursuit” means flirtation with distance, chase energy, teasing, anticipation, power dynamics of wanting/being wanted, or earning access. Answer for what reliably works for you (not occasional curiosity).', 16, true, '03009', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q17: 03010 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'In erotic contexts, I prefer:', 'This is about your comfort zone for “edginess.” “Safe/private/predictable” = minimal uncertainty, low vulnerability. “Small novelty” = gentle experiments within a safe container. “Balanced” = equal comfort with familiar and new. “Adventurous but controlled” = you like intensity/novelty but with clear boundaries. “High-risk/edgy/taboo-leaning” = you enjoy a strong thrill/edge, while still staying within consent and agreed limits. Choose the option that best matches your preferred level, not your partner’s.', 17, true, '03010', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Very safe/private/predictable', 'Very safe/private/predictable', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Mostly safe with small novelty', 'Mostly safe with small novelty', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Balanced', 'Balanced', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Adventurous but still controlled', 'Adventurous but still controlled', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'High-risk / edgy / taboo-leaning (within consent)', 'High-risk / edgy / taboo-leaning (within consent)', 5);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q18: 03011 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'Sex feels most fulfilling when it has a sacred/meaningful/ritual quality (not just pleasure).', '“Sacred/meaningful/ritual” can mean deep presence, emotional reverence, intentionality, symbolism, spirituality, or feeling like it connects you to something bigger than pleasure. You don’t need to be religious for this. Rate how important that meaning layer is for sex to feel truly fulfilling.', 18, true, '03011', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q19: 03012 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'Without some edge/taboo/intensity, sex can feel flat.', '“Edge/taboo/intensity” can mean strong energy, transgression fantasy, power play, risk flavor, or anything that feels a bit daring (always within consent). Rate whether you typically need that extra charge to stay engaged, versus being satisfied with gentle connection or straightforward pleasure.', 19, true, '03012', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q20: 03013 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'What sounds most arousing?', 'Choose what is most arousing in fantasy or real life when things are going well. “Being watched/admired” can include mirrors, feeling seen, or performance energy. “Watching my partner” means your arousal rises from observing their body, reactions, or pleasure. “Absorbed in sensation/connection” means attention is inward or relational, not observer-focused. Pick “Not sure” if none consistently stands out.', 20, true, '03013', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Being watched/admired (mirror, performance vibe)', 'Being watched/admired (mirror, performance vibe)', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Watching my partner / observing is hottest', 'Watching my partner / observing is hottest', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Neither—being absorbed in sensation/connection is hottest', 'Neither—being absorbed in sensation/connection is hottest', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Not sure', 'Not sure', 4);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q21: 03014 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I can usually reach orgasm with a partner when I want to.', 'Answer based on your typical experience with a partner over the last several months. “When I want to” means when you’re aiming for orgasm and conditions are reasonably good. Include whatever stimulation you usually use (manual, oral, toys, penetration, etc.). This is not a test of “normal,” just a practical signal for recommendations.', 21, true, '03014', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q22: 08002 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I generally feel secure in relationships.', '“Secure” means you usually feel worthy of love and trust that closeness is safe; you can handle distance without panic and handle conflict without shutting down completely. Answer based on your overall pattern across relationships, not only your current partner on a bad week.', 22, true, '08002', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q23: 08003 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'When my partner pulls away, I usually…', 'Think of a typical moment when you feel less contact/attention than you want (less texting, less affection, emotionally distant). Choose your most common first response. “Protest/get angry” means you react with frustration, criticism, or conflict to regain connection. “Self-soothe” means you can calm yourself and respond thoughtfully. Choose “Varies” only if there’s no dominant pattern.', 23, true, '08003', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Seek reassurance / pursue', 'Seek reassurance / pursue', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Shut down / withdraw', 'Shut down / withdraw', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Protest / get angry', 'Protest / get angry', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Self-soothe and stay grounded', 'Self-soothe and stay grounded', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Varies', 'Varies', 5);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q24: 08004 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Regarding interdependence in relationships, I tend to...', '“Interdependence” means being close while still being your own person. “Crave closeness” = you prefer lots of emotional/physical togetherness. “Keep distance” = you prefer more independence and space. “Balance both” = closeness feels good, and space feels good, without either being threatening. Answer for your usual preference, not your partner’s.', 24, true, '08004', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Crave closeness', 'Crave closeness', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Keep distance', 'Keep distance', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Balance both', 'Balance both', 3);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q25: 08005 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'After emotional repair (a good vulnerable talk), I often feel more desire.', '“Emotional repair” means resolving tension through honesty, empathy, apology, reassurance, or feeling understood again. Rate whether desire tends to return or increase after that kind of reconnection. Think of real examples, not what you hope happens.', 25, true, '08005', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q26: 08006 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'When I feel pressure (to perform, talk, or escalate), I shut down or want to withdraw.', '“Pressure” can be explicit (“we should have sex,” “are you close?”) or subtle (expectations, time pressure, feeling evaluated). “Shut down/withdraw” can mean going numb, losing arousal, wanting to stop, or emotionally checking out. Rate how reliably pressure triggers that response for you.', 26, true, '08006', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q27: 08012 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I lose interest when my partner becomes too emotionally dependent.', '“Emotionally dependent” means your partner relies on you heavily for reassurance, mood regulation, or identity, in a way that feels like pressure or responsibility. Rate your typical reaction: does increased dependence reduce attraction/interest for you? Answer honestly; this is used to tailor relationship and intimacy guidance.', 27, true, '08012', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q28: 09013 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I sometimes use flirtation/sex to influence the dynamic or get needs met.”', 'This is about using sexuality as leverage (to gain closeness, avoid conflict, get reassurance, feel secure, gain power, or steer the relationship). It doesn’t mean you’re “bad”; it’s a pattern some people use under stress. Answer based on real behavior, not intention. If it happens rarely, choose a lower number.', 28, true, '09013', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q29: 10002 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'During intimacy, how do you prefer to communicate your needs and desires?', 'Answer for what feels best and most natural in the moment (not what you think you should do). “Nonverbal/quiet” = little talking. “Touch/movement” = guiding hands, pressure, pace. “Short phrases” = brief cues like “slower,” “yes,” “right there.” “Ongoing verbal feedback” = frequent talking about what feels good. “Relational check-ins” = naming feelings and connection needs (comfort, reassurance, emotional attunement) during intimacy.', 29, true, '10002', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Mostly nonverbal / quiet', 'Mostly nonverbal / quiet', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Mainly through touch/movement', 'Mainly through touch/movement', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Short clear phrases (“slower / like that”)', 'Short clear phrases (“slower / like that”)', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Expressive, ongoing verbal feedback', 'Expressive, ongoing verbal feedback', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Emotionally transparent + relational check-ins', 'Emotionally transparent + relational check-ins', 5);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q30: 10003 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I’m comfortable expressing what turns me on.', 'Rate your comfort in real situations: can you share desires (words, texts, guiding touch) without strong embarrassment or fear of judgment? Include both during sex and outside of sex. Answer based on typical comfort, not your best-day confidence.', 30, true, '10003', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q31: 10004 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I’m comfortable expressing what I don’t want.', 'This is about stating limits clearly (saying no, slowing down, redirecting, naming boundaries) without freezing, fawning, or feeling guilty. Rate your usual ability, especially in the moment.', 31, true, '10004', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q32: 10005 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'If my partner is quiet/neutral during sex, my arousal drops.', '“Quiet/neutral” means minimal reaction, little sound, little feedback, hard to read. Rate whether you reliably lose arousal in that situation, even if touch continues. This is about your nervous system response, not about blaming your partner.', 32, true, '10005', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q33: 11001 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Which dynamic feels most natural?', 'This is about the flow of influence during sex (who initiates, guides, sets pace). “Lead/direct” can be gentle or firm. “Surrender/be led” means you relax more when someone else guides. “Switching” means you genuinely like both depending on mood/partner. “Egalitarian/no roles” means you prefer co-leading without clear roles. Choose what feels easiest and most energizing, not what feels politically correct.', 33, true, '11001', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I like to lead/direct', 'I like to lead/direct', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I like to surrender/be led', 'I like to surrender/be led', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I like switching depending on mood', 'I like switching depending on mood', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I prefer egalitarian/no roles', 'I prefer egalitarian/no roles', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Not sure / depends a lot', 'Not sure / depends a lot', 5);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q34: 11002 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I enjoy clear structure/protocol/rules in sexual dynamics.', '“Structure/protocol/rules” can be light (a routine, a sequence, agreements like “ask before escalation”) or more formal (roles, rituals, clear scripts). Rate whether clear structure makes sex feel safer, hotter, or easier for you.', 34, true, '11002', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q35: 11003 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'In sex I most naturally…', 'Choose what you tend to do by default when you’re not overthinking. “Partner’s pleasure first” means you prioritize their experience and often take responsibility for it. “Mutual balance” means you track both equally. “Prefer receiving/being guided” means you relax and enjoy more when you’re the focus or when you’re being led. Choose “Varies” only if there’s no clear default across time/partners.', 35, true, '11003', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Focus on my partner’s pleasure first', 'Focus on my partner’s pleasure first', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Focus on mutual balance', 'Focus on mutual balance', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Prefer receiving/being guided', 'Prefer receiving/being guided', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'It varies a lot', 'It varies a lot', 4);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q36: 11004 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I feel most connected sexually when I’m soothing or stabilizing my partner’s emotions.', '“Soothing/stabilizing” means calming, reassuring, grounding, helping your partner feel safe, regulated, or emotionally held. Rate whether that role increases your sense of sexual connection and desire, versus pulling you out of erotic energy.', 36, true, '11004', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q37: 14020 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'What most reliably motivates you to want sex?', 'Pick the main reason you seek sex when it’s at its best for you (your primary driver). “Motivates” means what pulls you toward sex, not what makes sex good once you’re already in it. If two feel true, choose the one that most consistently initiates your desire. Quick definitions: Bonding = closeness; Pleasure/play = fun/body enjoyment; Novelty = newness; Intensity/edge = charge/thrill; Validation = feeling desired; Power = leading/surrendering; Meaning = sacred/union; Comfort = routine closeness; Service = giving pleasure; Healing/repair = soothing after stress/conflict; Escape = turning off your mind/world.', 37, true, '14020', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Bonding / intimacy', 'Bonding / intimacy', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Pleasure / play', 'Pleasure / play', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Novelty / exploration', 'Novelty / exploration', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Intensity / edge / taboo energy', 'Intensity / edge / taboo energy', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Validation / being desired', 'Validation / being desired', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Power (leading or surrendering)', 'Power (leading or surrendering)', 6);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Meaning / spiritual union', 'Meaning / spiritual union', 7);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Comfort / routine closeness', 'Comfort / routine closeness', 8);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Service (giving pleasure)', 'Service (giving pleasure)', 9);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Healing / repair / nervous-system soothing', 'Healing / repair / nervous-system soothing', 10);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Escape / shutting off the world', 'Escape / shutting off the world', 11);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q38: 14021 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'I seek intense sex to escape numbness/stress or to feel something.', 'This is about using intensity as a regulator: when stressed, disconnected, or numb, do you look for stronger stimulation to shift your state? Answer based on a recurring pattern (especially under stress), not a one-off experience.', 38, true, '14021', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q39: 15001 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Which country do you live in?', 'Choose the country where you currently live most of the time (your main residence). If you split time between countries, pick the one you spend the majority of the year in.', 39, true, '15001', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'DIN Countries', 'DIN Countries', 1);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q40: 15002 (open)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('open', 'Which ZIP / postal code do you live in?', 'Enter your current postal code for your main residence. If you’re privacy-conscious, you can enter only the first part (for example, first 3–4 characters) as long as it still represents your area. Avoid adding extra address details. Examples: 11000; 94110; SW1A 1AA', 40, true, '15002', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q41: 15003 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Which age range are you in?', 'This helps normalize results across life stages (for example, hormonal changes, stress load, relationship phase), not to judge you.', 41, true, '15003', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '18–24', '18–24', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '25–34', '25–34', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '35–44', '35–44', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '45–54', '45–54', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '55–64', '55–64', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '65+', '65+', 6);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q42: 15004 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'What relationship structure are you currently in?', 'Choose what best describes your current structure. Quick definitions: Monogamous = exclusive; Monogamish = mostly exclusive with limited exceptions; Open = non-exclusive with agreements; Polyamorous = multiple committed relationships are possible; Solo-poly = poly while prioritizing personal autonomy (not nesting/merging lives); Fluid/Undefined = not clearly defined right now. Pick the closest match.', 42, true, '15004', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Single', 'Single', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Monogamous', 'Monogamous', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Monogamish', 'Monogamish', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Open', 'Open', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Polyamorous', 'Polyamorous', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Solo-poly', 'Solo-poly', 6);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Fluid / Undefined', 'Fluid / Undefined', 7);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q43: 15005 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Do you have children?', 'Choose the option that reflects your current caregiving load. If you have multiple children, answer based on your youngest child (since that most affects time, sleep, stress, and intimacy logistics).', 43, true, '15005', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'No', 'No', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, youngest child is 0–3 years', 'Yes, youngest child is 0–3 years', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, youngest child is 4–10 years', 'Yes, youngest child is 4–10 years', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, youngest child is 11–17 years', 'Yes, youngest child is 11–17 years', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, children are 18+ and live with me', 'Yes, children are 18+ and live with me', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, children are 18+ and do not live with me', 'Yes, children are 18+ and do not live with me', 6);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Prefer not to answer', 'Prefer not to answer', 7);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q44: 15006 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'How high is your overall stress level most of the time?', 'Think of your baseline stress across most days in the last month (workload, worry, nervous-system tension). “High” means stress noticeably affects your mood, energy, or patience; “Very high” means it often feels overwhelming or hard to come down from.', 44, true, '15006', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Very low', 'Very low', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Low', 'Low', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Medium', 'Medium', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'High', 'High', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Very high', 'Very high', 5);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q45: 15007 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'How rested do you usually feel when you wake up?', 'Answer for a typical morning over the last 2–4 weeks, not your best or worst night. Consider both physical rest and mental freshness. If your sleep varies, pick the most common option.', 45, true, '15007', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Very rested', 'Very rested', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Rather rested', 'Rather rested', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'In between', 'In between', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Rather tired', 'Rather tired', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Very tired', 'Very tired', 5);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q46: 15008 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Do you live with any long-term physical or mental health conditions that affect your energy, mood or everyday functioning?', 'This is about ongoing conditions (not a short cold) that meaningfully affect your daily functioning. You don’t need to share diagnoses here. If you’re uncertain whether something “counts,” choose “I’m not sure.” Choose “Prefer not to answer” if you’d rather not share.', 46, true, '15008', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'No', 'No', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, mainly physical health', 'Yes, mainly physical health', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, mainly mental health', 'Yes, mainly mental health', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, both physical and mental health', 'Yes, both physical and mental health', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I’m not sure', 'I’m not sure', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Prefer not to answer', 'Prefer not to answer', 6);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q47: 15009 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Are you currently taking any medication or hormones that you feel might influence your energy, mood or sexual drive (for example antidepressants, hormonal contraception, testosterone, etc.)?', 'Answer based on your own observation, not what you’ve heard. Include prescriptions, hormonal contraception, HRT, testosterone, SSRIs/SNRIs, etc. If you take something but you can’t tell its effect, choose “I’m not sure.” No need to list the medication here.', 47, true, '15009', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'No', 'No', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, and I feel they lower my drive', 'Yes, and I feel they lower my drive', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, and I feel they increase my drive', 'Yes, and I feel they increase my drive', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Yes, but I’m not sure how they affect my drive', 'Yes, but I’m not sure how they affect my drive', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Prefer not to answer', 'Prefer not to answer', 5);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q48: 15010 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'What is your gender identity?', 'Choose the option that best matches how you identify now. If none fits, choose “Other” (if you’ll be able to specify later) or “Prefer not to say.” Answering is optional and won’t change your value or access to results.', 48, true, '15010', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Woman', 'Woman', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Man', 'Man', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Nonbinary', 'Nonbinary', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Other', 'Other', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I’d rather not label this', 'I’d rather not label this', 5);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q49: 15011 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'What is your sexual orientation?', 'Choose the label that best fits your enduring pattern of attraction. If you’re unsure or your label is different, choose “Queer” or “Other” (depending on what fits you best). This is for tailoring language and norms, not for assumptions about behavior.', 49, true, '15011', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Heterosexual', 'Heterosexual', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Homosexual', 'Homosexual', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Bisexual', 'Bisexual', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Pansexual', 'Pansexual', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Queer', 'Queer', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Questioning / exploring', 'Questioning / exploring', 6);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Other', 'Other', 7);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I don''t use a label', 'I don''t use a label', 8);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q50: 16001 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'If ONE thing changed in the next 3 months, your sex life would feel meaningfully better. Which is closest?', 'Choose the one shift that would create the biggest ripple effect over the next 3 months. If multiple options feel true, pick the one that would make everything else easier. ‘Other’ is great if your real goal doesn’t fit the list.', 50, true, '16001', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Desire & arousal (wanting sex more / getting turned on more easily)', 'Desire & arousal (wanting sex more / getting turned on more easily)', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Pleasure & orgasm (enjoying sex more / reaching orgasm)', 'Pleasure & orgasm (enjoying sex more / reaching orgasm)', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Pain, discomfort, or physical barriers', 'Pain, discomfort, or physical barriers', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Emotional safety & connection', 'Emotional safety & connection', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Communication (naming needs, limits, fantasies)', 'Communication (naming needs, limits, fantasies)', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Novelty & excitement', 'Novelty & excitement', 6);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Confidence & body comfort', 'Confidence & body comfort', 7);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Healing / repair from past experiences', 'Healing / repair from past experiences', 8);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Partner alignment (mismatched desire, roles, expectations)', 'Partner alignment (mismatched desire, roles, expectations)', 9);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Other (short text)', 'Other (short text)', 10);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q51: 16002 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'How important is it for you to work on this right now?', 'This is about your priorities—not what you think you should want. Go with your gut: 1 = not a priority right now, 7 = top of mind / deeply important.', 51, true, '16002', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q52: 16003 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'How possible does change feel in the next 3–6 months?', 'Imagine the next 3–6 months with your real schedule, energy, and relationship dynamics included. 1 = feels out of reach, 7 = feels genuinely doable (even if it’s not easy).', 52, true, '16003', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q53: 16004 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'If you had a clear plan that felt like a good fit, when would you realistically start?', 'Assume you had a plan that feels like a good fit—clear, doable, and aligned. When would you actually begin in your real calendar (not a fantasy week)? Choose the closest option.', 53, true, '16004', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Within 7 days', 'Within 7 days', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Within 30 days', 'Within 30 days', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '1–3 months', '1–3 months', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '3–6 months', '3–6 months', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '6–12 months', '6–12 months', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Later than 12 months', 'Later than 12 months', 6);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Not sure yet', 'Not sure yet', 7);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q54: 16005 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'When you reflect on your current sexuality and pleasure, which description feels most true for you?', 'Think of this as your current season, not a permanent label. Choose the phase that best describes your baseline most days lately (past 4–8 weeks), even if you sometimes fluctuate.', 54, true, '16005', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Recharging / Pausing – I’m in a quieter, restorative phase of my sexual life. Desire feels gentle or distant, and that’s okay. I sense I’m gathering energy, letting my body and mind rest before passion naturally reawakens.', 'Recharging / Pausing – I’m in a quieter, restorative phase of my sexual life. Desire feels gentle or distant, and that’s okay. I sense I’m gathering energy, letting my body and mind rest before passion naturally reawakens.', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Repairing / Reconnecting – I’m rebuilding my relationship to sexuality, healing from past pain, shame, or disconnection. My focus is on safety, trust, and emotional openness — learning to feel at home in my body again.', 'Repairing / Reconnecting – I’m rebuilding my relationship to sexuality, healing from past pain, shame, or disconnection. My focus is on safety, trust, and emotional openness — learning to feel at home in my body again.', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Awakening / Exploring – I feel curious and alive with possibility. I’m discovering what turns me on, learning through play and experimentation, and beginning to express my desires with more ease and honesty.', 'Awakening / Exploring – I feel curious and alive with possibility. I’m discovering what turns me on, learning through play and experimentation, and beginning to express my desires with more ease and honesty.', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Expanding / Experimenting – I feel confident and expressive in my sexuality. I enjoy exploring new experiences, sensations, and dynamics, communicating openly about my desires, and co-creating pleasure with my partner(s).', 'Expanding / Experimenting – I feel confident and expressive in my sexuality. I enjoy exploring new experiences, sensations, and dynamics, communicating openly about my desires, and co-creating pleasure with my partner(s).', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Grounded / Integrated - I experience sexuality as a stable, integrated part of my life. Desire feels steady and familiar. Pleasure arises naturally in connection, routine, or self-care. This phase is about maintaining fulfillment with presence and appreciation, rather than chasing newness or repair.', 'Grounded / Integrated - I experience sexuality as a stable, integrated part of my life. Desire feels steady and familiar. Pleasure arises naturally in connection, routine, or self-care. This phase is about maintaining fulfillment with presence and appreciation, rather than chasing newness or repair.', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Evolving / Transcending – I experience sexuality as a deeper, transformative force — a way to connect with creativity, love, and spirituality. Pleasure feels like presence, flow, and expansion beyond the physical.', 'Evolving / Transcending – I experience sexuality as a deeper, transformative force — a way to connect with creativity, love, and spirituality. Pleasure feels like presence, flow, and expansion beyond the physical.', 6);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q55: 16006 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'Where would you like your sexuality to be in 3–6 months?', 'Now pick your north star—where you’d like to be in 3–6 months if things improved. It can be aspirational, but try to keep it believable for your life. This helps tailor the recommendations and pacing.', 55, true, '16006', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Recharging / Pausing – I’m in a quieter, restorative phase of my sexual life. Desire feels gentle or distant, and that’s okay. I sense I’m gathering energy, letting my body and mind rest before passion naturally reawakens.', 'Recharging / Pausing – I’m in a quieter, restorative phase of my sexual life. Desire feels gentle or distant, and that’s okay. I sense I’m gathering energy, letting my body and mind rest before passion naturally reawakens.', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Repairing / Reconnecting – I’m rebuilding my relationship to sexuality, healing from past pain, shame, or disconnection. My focus is on safety, trust, and emotional openness — learning to feel at home in my body again.', 'Repairing / Reconnecting – I’m rebuilding my relationship to sexuality, healing from past pain, shame, or disconnection. My focus is on safety, trust, and emotional openness — learning to feel at home in my body again.', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Awakening / Exploring – I feel curious and alive with possibility. I’m discovering what turns me on, learning through play and experimentation, and beginning to express my desires with more ease and honesty.', 'Awakening / Exploring – I feel curious and alive with possibility. I’m discovering what turns me on, learning through play and experimentation, and beginning to express my desires with more ease and honesty.', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Expanding / Experimenting – I feel confident and expressive in my sexuality. I enjoy exploring new experiences, sensations, and dynamics, communicating openly about my desires, and co-creating pleasure with my partner(s).', 'Expanding / Experimenting – I feel confident and expressive in my sexuality. I enjoy exploring new experiences, sensations, and dynamics, communicating openly about my desires, and co-creating pleasure with my partner(s).', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Grounded / Integrated - I experience sexuality as a stable, integrated part of my life. Desire feels steady and familiar. Pleasure arises naturally in connection, routine, or self-care. This phase is about maintaining fulfillment with presence and appreciation, rather than chasing newness or repair.', 'Grounded / Integrated - I experience sexuality as a stable, integrated part of my life. Desire feels steady and familiar. Pleasure arises naturally in connection, routine, or self-care. This phase is about maintaining fulfillment with presence and appreciation, rather than chasing newness or repair.', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Evolving / Transcending – I experience sexuality as a deeper, transformative force — a way to connect with creativity, love, and spirituality. Pleasure feels like presence, flow, and expansion beyond the physical.', 'Evolving / Transcending – I experience sexuality as a deeper, transformative force — a way to connect with creativity, love, and spirituality. Pleasure feels like presence, flow, and expansion beyond the physical.', 6);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q56: 16007 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'When you want to improve something important in your life (health, relationships, confidence), what do you usually do first?', 'Be honest about what actually gets you moving—not what sounds ideal. Think of past changes you’ve stuck with: what typically helps you go from ‘I should’ to ‘I’m doing’?', 56, true, '16007', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I research on my own (articles/videos/free resources)', 'I research on my own (articles/videos/free resources)', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I use a structured tool/app/journal to guide me', 'I use a structured tool/app/journal to guide me', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I follow a program/course with steps', 'I follow a program/course with steps', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I prefer working with a professional (coach/therapist/mentor)', 'I prefer working with a professional (coach/therapist/mentor)', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I usually don’t take action unless it becomes urgent', 'I usually don’t take action unless it becomes urgent', 5);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q57: 16008 (multiple)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('multiple', 'What kind of support would feel most helpful for your top focus?', 'Select the kinds of support that would make this easier. If you can, choose what would help most right now (not what you ‘should’ want). ‘Not sure yet’ is a completely valid answer.', 57, true, '16008', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Self-guided tools & exercises', 'Self-guided tools & exercises', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Short structured program (2–4 weeks)', 'Short structured program (2–4 weeks)', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Live group experience', 'Live group experience', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Partner-inclusive guidance', 'Partner-inclusive guidance', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '1:1 professional support', '1:1 professional support', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Not sure yet', 'Not sure yet', 6);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q58: 16011 (multiple)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('multiple', 'Which of the following do you regularly use?', 'Select what you use regularly (at least monthly). This helps us understand what types of support/subscriptions you’re already comfortable with.', 58, true, '16011', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Spotify Premium', 'Spotify Premium', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Therapy / coaching', 'Therapy / coaching', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Meditation apps', 'Meditation apps', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Other paid subscriptions (e.g., Netflix, paid apps)', 'Other paid subscriptions (e.g., Netflix, paid apps)', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Other (please specify)', 'Other (please specify)', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'None', 'None', 6);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q59: 16012 (single)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('single', 'About how much do you typically invest per year in personal growth (books, courses, therapy/coaching, apps)?', 'A rough estimate is fine. Include books, courses, therapy/coaching, and paid apps/subscriptions (one-offs + ongoing).', 59, true, '16012', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '€0', '€0', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Up to €50', 'Up to €50', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Up to €200', 'Up to €200', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, '€1,000+', '€1,000+', 4);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q60: 16013 (scale)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('scale', 'How important is understanding your sexuality for your life?', 'Rate how central this feels for you right now. 1 = not important, 7 = extremely important.', 60, true, '16013', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

  -- Q61: 16014 (multiple)
  INSERT INTO survey_question (type, question, subinfo, display_order, required, frontend_qid, status)
  VALUES ('multiple', 'Which things are in the way? (Select all that apply)', 'Select anything that’s genuinely in the way right now. This isn’t a verdict—it’s a map. The more real you are here, the more precisely we can tailor your next steps. If none fit well, choose ‘Other.’', 61, true, '16014', 'active')
  RETURNING id INTO v_q_id;
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I’m not sure what would help', 'I’m not sure what would help', 1);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Time/energy is limited', 'Time/energy is limited', 2);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Partner isn’t aligned/engaged', 'Partner isn’t aligned/engaged', 3);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Emotional safety isn’t there yet', 'Emotional safety isn’t there yet', 4);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Shame / pressure / self-judgment', 'Shame / pressure / self-judgment', 5);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Physical pain/body issues', 'Physical pain/body issues', 6);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Cost/access', 'Cost/access', 7);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'I lose motivation over time', 'I lose motivation over time', 8);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'No major obstacles', 'No major obstacles', 9);
  INSERT INTO answer_option (survey_question_id, option_text, option_value, display_order)
  VALUES (v_q_id, 'Other', 'Other', 10);
  INSERT INTO survey_question_mapping (survey_id, question_id) VALUES (v_survey_id, v_q_id);

END $$;

COMMIT;
