-- Migration: Admin Segment Builder
-- Creates admin_segment table and get_segment_match_count RPC

-- ============================================
-- 1. admin_segment table
-- ============================================

CREATE TABLE IF NOT EXISTS admin_segment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_email text NOT NULL,
  name text NOT NULL,
  description text,
  rules jsonb NOT NULL,
  is_shared boolean NOT NULL DEFAULT false,
  match_count integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_admin_segment_email ON admin_segment(admin_email);

-- Enable RLS
ALTER TABLE admin_segment ENABLE ROW LEVEL SECURITY;

-- Policy: Only service role can access (no public access)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'admin_segment' AND policyname = 'Service role full access'
  ) THEN
    CREATE POLICY "Service role full access" ON admin_segment
      FOR ALL TO service_role
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

-- ============================================
-- 2. get_segment_match_count RPC
-- ============================================

CREATE OR REPLACE FUNCTION get_segment_match_count(p_rules jsonb)
RETURNS JSON
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_logic text;
  v_conditions jsonb;
  v_cond jsonb;
  v_field text;
  v_operator text;
  v_value text;
  v_clause text;
  v_clauses text[] := ARRAY[]::text[];
  v_joiner text;
  v_where text;
  v_sql text;
  v_count integer;
  v_sample json;
  result json;
BEGIN
  -- Extract logic and conditions from rules
  v_logic := p_rules->>'logic';
  v_conditions := p_rules->'conditions';

  IF v_logic IS NULL OR v_conditions IS NULL THEN
    RAISE EXCEPTION 'Invalid rules: missing logic or conditions';
  END IF;

  IF v_logic = 'and' THEN
    v_joiner := ' AND ';
  ELSIF v_logic = 'or' THEN
    v_joiner := ' OR ';
  ELSE
    RAISE EXCEPTION 'Invalid logic: must be "and" or "or"';
  END IF;

  -- Build WHERE clauses from conditions
  FOR v_cond IN SELECT * FROM jsonb_array_elements(v_conditions)
  LOOP
    v_field := v_cond->>'field';
    v_operator := v_cond->>'operator';
    v_value := v_cond->>'value';

    -- Map field to SQL column
    IF v_field = 'archetype' THEN
      v_clause := format('sr.primary_archetype');
    ELSIF v_field = 'v5_archetype' THEN
      v_clause := format('sr.v5_primary_archetype');
    ELSIF v_field = 'gender' THEN
      v_clause := format('up.gender');
    ELSIF v_field = 'sexual_orientation' THEN
      v_clause := format('up.sexual_orientation');
    ELSIF v_field = 'relationship_status' THEN
      v_clause := format('up.relationship_status');
    ELSIF v_field = 'country' THEN
      v_clause := format('up.location_primary');
    ELSIF v_field = 'status' THEN
      v_clause := format('ss.status');
    ELSIF v_field = 'duration_ms' THEN
      v_clause := format('ss.duration_ms');
    ELSIF v_field = 'created_date_time' THEN
      v_clause := format('ss.created_date_time');
    ELSIF v_field = 'utm_source' THEN
      v_clause := format('ss.utm_tracker::jsonb->>%L', 'utm_source');
    ELSIF v_field = 'utm_medium' THEN
      v_clause := format('ss.utm_tracker::jsonb->>%L', 'utm_medium');
    ELSIF v_field = 'has_report' THEN
      IF v_value = 'true' THEN
        v_clauses := array_append(v_clauses,
          'EXISTS (SELECT 1 FROM personal_report pr WHERE pr.survey_submission_id = ss.id)');
      ELSE
        v_clauses := array_append(v_clauses,
          'NOT EXISTS (SELECT 1 FROM personal_report pr WHERE pr.survey_submission_id = ss.id)');
      END IF;
      CONTINUE;
    ELSIF v_field = 'has_payment' THEN
      IF v_value = 'true' THEN
        v_clauses := array_append(v_clauses,
          format('EXISTS (SELECT 1 FROM personal_report pr2 JOIN payment p ON p.personal_report_id = pr2.id WHERE pr2.survey_submission_id = ss.id AND p.status = %L)', 'succeeded'));
      ELSE
        v_clauses := array_append(v_clauses,
          format('NOT EXISTS (SELECT 1 FROM personal_report pr2 JOIN payment p ON p.personal_report_id = pr2.id WHERE pr2.survey_submission_id = ss.id AND p.status = %L)', 'succeeded'));
      END IF;
      CONTINUE;
    ELSE
      RAISE EXCEPTION 'Unknown field: %', v_field;
    END IF;

    -- Apply operator
    IF v_operator = 'eq' THEN
      v_clauses := array_append(v_clauses, format('%s = %L', v_clause, v_value));
    ELSIF v_operator = 'neq' THEN
      v_clauses := array_append(v_clauses, format('%s != %L', v_clause, v_value));
    ELSIF v_operator = 'lt' THEN
      v_clauses := array_append(v_clauses, format('%s < %L', v_clause, v_value));
    ELSIF v_operator = 'gt' THEN
      v_clauses := array_append(v_clauses, format('%s > %L', v_clause, v_value));
    ELSIF v_operator = 'lte' THEN
      v_clauses := array_append(v_clauses, format('%s <= %L', v_clause, v_value));
    ELSIF v_operator = 'gte' THEN
      v_clauses := array_append(v_clauses, format('%s >= %L', v_clause, v_value));
    ELSIF v_operator = 'contains' THEN
      v_clauses := array_append(v_clauses, format('%s ILIKE %L', v_clause, '%' || v_value || '%'));
    ELSE
      RAISE EXCEPTION 'Unknown operator: %', v_operator;
    END IF;
  END LOOP;

  -- Build final WHERE clause
  IF array_length(v_clauses, 1) IS NULL OR array_length(v_clauses, 1) = 0 THEN
    RAISE EXCEPTION 'No valid conditions';
  END IF;

  v_where := array_to_string(v_clauses, v_joiner);

  -- Count query
  v_sql := format(
    'SELECT count(*) FROM survey_submission ss
     LEFT JOIN scoring_result sr ON sr.survey_submission_id = ss.id
     LEFT JOIN app_user au ON au.id = ss.user_id
     LEFT JOIN user_profile up ON up.id = au.user_profile_id
     WHERE %s',
    v_where
  );

  EXECUTE v_sql INTO v_count;

  -- Sample query (first 10 rows)
  v_sql := format(
    'SELECT json_agg(t) FROM (
       SELECT ss.id, au.email, sr.primary_archetype AS archetype,
              ss.created_date_time, ss.status, ss.duration_ms
       FROM survey_submission ss
       LEFT JOIN scoring_result sr ON sr.survey_submission_id = ss.id
       LEFT JOIN app_user au ON au.id = ss.user_id
       LEFT JOIN user_profile up ON up.id = au.user_profile_id
       WHERE %s
       ORDER BY ss.created_date_time DESC
       LIMIT 10
     ) t',
    v_where
  );

  EXECUTE v_sql INTO v_sample;

  -- Return combined result
  SELECT json_build_object(
    'count', v_count,
    'sample', COALESCE(v_sample, '[]'::json)
  ) INTO result;

  RETURN result;
END;
$$;

GRANT EXECUTE ON FUNCTION get_segment_match_count(jsonb) TO service_role;;
